version: '3'

services:
  todosDB:
    image: postgres:15.2
    container_name: todos-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todosnext
    volumes:
      - ./postgres:/var/lib/postgresql/data